const dropArea = document.getElementById("drop-area");
const getExcelInput = document.getElementById("get_excel_input");
const toggleTableBtn = document.getElementById("toggle-table");
const table = document.querySelector("table");
const tableContainer = document.querySelector(".table-container");
const treeContainer = document.querySelector(".graph");
const controlPanel = document.querySelector(".buttons");
const increaseRowSelect = document.querySelector("select");
const currRowsSpan = document.getElementById("curr-rows");
const totalRowsSpan = document.getElementById("total-rows");
const showRowBtn = document.getElementById("show-row");
const graphBtns = document.querySelector(".graph-btns");
const alertEl = document.getElementById("alert");

var starty, startx, scrleft, scrtop, isdown; // for drag scroll
var scale = 1; // zoom scale

var root;

var currRows = 0;
var increaseRow = 5;
var pureData;
var nodeNumber = 0; // This and treeHeight just for setting svg size
var treeHeight = 0;
var totalRows = 0;
var attributes = {}; // store data attributes for select option
var predAttributes = {}; // data for prediction
var predictedNode = null;

const defaultDataSet = {
  Sheets: {
    Sayfa1: {
      "!ref": "A1:E15",
      A1: {
        t: "s",
        v: "Outlook",
        r: "<t>Outlook</t>",
        h: "Outlook",
        w: "Outlook",
      },
      B1: {
        t: "s",
        v: "Temprature",
        r: "<t>Temprature</t>",
        h: "Temprature",
        w: "Temprature",
      },
      C1: {
        t: "s",
        v: "Humidity",
        r: "<t>Humidity</t>",
        h: "Humidity",
        w: "Humidity",
      },
      D1: {
        t: "s",
        v: "Wind",
        r: "<t>Wind</t>",
        h: "Wind",
        w: "Wind",
      },
      E1: {
        t: "s",
        v: "Play",
        r: "<t>Play</t>",
        h: "Play",
        w: "Play",
      },
      A2: {
        t: "s",
        v: "Sunny",
        r: "<t>Sunny</t>",
        h: "Sunny",
        w: "Sunny",
      },
      B2: {
        t: "s",
        v: "Hot",
        r: "<t>Hot</t>",
        h: "Hot",
        w: "Hot",
      },
      C2: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D2: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E2: {
        t: "s",
        v: "No",
        r: "<t>No</t>",
        h: "No",
        w: "No",
      },
      A3: {
        t: "s",
        v: "Sunny",
        r: "<t>Sunny</t>",
        h: "Sunny",
        w: "Sunny",
      },
      B3: {
        t: "s",
        v: "Hot",
        r: "<t>Hot</t>",
        h: "Hot",
        w: "Hot",
      },
      C3: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D3: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E3: {
        t: "s",
        v: "No",
        r: "<t>No</t>",
        h: "No",
        w: "No",
      },
      A4: {
        t: "s",
        v: "Overcast",
        r: "<t>Overcast</t>",
        h: "Overcast",
        w: "Overcast",
      },
      B4: {
        t: "s",
        v: "Hot",
        r: "<t>Hot</t>",
        h: "Hot",
        w: "Hot",
      },
      C4: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D4: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E4: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A5: {
        t: "s",
        v: "Rain",
        r: "<t>Rain</t>",
        h: "Rain",
        w: "Rain",
      },
      B5: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C5: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D5: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E5: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A6: {
        t: "s",
        v: "Rain",
        r: "<t>Rain</t>",
        h: "Rain",
        w: "Rain",
      },
      B6: {
        t: "s",
        v: "Cool",
        r: "<t>Cool</t>",
        h: "Cool",
        w: "Cool",
      },
      C6: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D6: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E6: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A7: {
        t: "s",
        v: "Rain",
        r: "<t>Rain</t>",
        h: "Rain",
        w: "Rain",
      },
      B7: {
        t: "s",
        v: "Cool",
        r: "<t>Cool</t>",
        h: "Cool",
        w: "Cool",
      },
      C7: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D7: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E7: {
        t: "s",
        v: "No",
        r: "<t>No</t>",
        h: "No",
        w: "No",
      },
      A8: {
        t: "s",
        v: "Overcast",
        r: "<t>Overcast</t>",
        h: "Overcast",
        w: "Overcast",
      },
      B8: {
        t: "s",
        v: "Cool",
        r: "<t>Cool</t>",
        h: "Cool",
        w: "Cool",
      },
      C8: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D8: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E8: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A9: {
        t: "s",
        v: "Sunny",
        r: "<t>Sunny</t>",
        h: "Sunny",
        w: "Sunny",
      },
      B9: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C9: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D9: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E9: {
        t: "s",
        v: "No",
        r: "<t>No</t>",
        h: "No",
        w: "No",
      },
      A10: {
        t: "s",
        v: "Sunny",
        r: "<t>Sunny</t>",
        h: "Sunny",
        w: "Sunny",
      },
      B10: {
        t: "s",
        v: "Cool",
        r: "<t>Cool</t>",
        h: "Cool",
        w: "Cool",
      },
      C10: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D10: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E10: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A11: {
        t: "s",
        v: "Rain",
        r: "<t>Rain</t>",
        h: "Rain",
        w: "Rain",
      },
      B11: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C11: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D11: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E11: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A12: {
        t: "s",
        v: "Sunny",
        r: "<t>Sunny</t>",
        h: "Sunny",
        w: "Sunny",
      },
      B12: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C12: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D12: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E12: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A13: {
        t: "s",
        v: "Overcast",
        r: "<t>Overcast</t>",
        h: "Overcast",
        w: "Overcast",
      },
      B13: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C13: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D13: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E13: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A14: {
        t: "s",
        v: "Overcast",
        r: "<t>Overcast</t>",
        h: "Overcast",
        w: "Overcast",
      },
      B14: {
        t: "s",
        v: "Hot",
        r: "<t>Hot</t>",
        h: "Hot",
        w: "Hot",
      },
      C14: {
        t: "s",
        v: "Normal",
        r: "<t>Normal</t>",
        h: "Normal",
        w: "Normal",
      },
      D14: {
        t: "s",
        v: "Weak",
        r: "<t>Weak</t>",
        h: "Weak",
        w: "Weak",
      },
      E14: {
        t: "s",
        v: "Yes",
        r: "<t>Yes</t>",
        h: "Yes",
        w: "Yes",
      },
      A15: {
        t: "s",
        v: "Rain",
        r: "<t>Rain</t>",
        h: "Rain",
        w: "Rain",
      },
      B15: {
        t: "s",
        v: "Mild",
        r: "<t>Mild</t>",
        h: "Mild",
        w: "Mild",
      },
      C15: {
        t: "s",
        v: "High",
        r: "<t>High</t>",
        h: "High",
        w: "High",
      },
      D15: {
        t: "s",
        v: "Strong",
        r: "<t>Strong</t>",
        h: "Strong",
        w: "Strong",
      },
      E15: {
        t: "s",
        v: "No",
        r: "<t>No</t>",
        h: "No",
        w: "No",
      },
      "!margins": {
        left: 0.7,
        right: 0.7,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3,
      },
    },
  },
  SheetNames: ["Sayfa1"],
};
